version: "3.8"

services:
    mysqldb:
        image: mysql:5.7
        container_name: teddy-mysql
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_TCP_PORT=$MYSQL_DOCKER_PORT
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        expose:
            - $MYSQL_DOCKER_PORT
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
    redis:
        image: redis:alpine
        container_name: redis
        ports:
        - $REDIS_PORT:$REDIS_PORT
    app:
        depends_on:
            mysqldb:
                condition: service_healthy
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /usr/src/teddy
        container_name: teddy-api
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_HOST=mysqldb
            - MYSQL_LOCAL_PORT=$MYSQL_DOCKER_PORT
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_USERNAME=$MYSQL_USERNAME
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - JWT_SECRET_KEY=$JWT_SECRET_KEY
        ports:
            - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
        stdin_open: true
        tty: true